# Generated by Django 3.1.7 on 2021-10-28 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('coat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('numberOfRatings', models.IntegerField(default=0)),
                ('obtainScore', models.FloatField(default=0)),
                ('totalRating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='judgeTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgeTag', to='judge.tags')),
                ('user', models.ManyToManyField(blank=True, related_name='usersInTag', to='judge.tags')),
            ],
        ),
        migrations.CreateModel(
            name='judgeRateing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, max_length=9999, null=True)),
                ('cannon1', models.CharField(blank=True, max_length=200, null=True)),
                ('cannon2', models.CharField(blank=True, max_length=200, null=True)),
                ('cannon3', models.CharField(blank=True, max_length=200, null=True)),
                ('cannon4', models.CharField(blank=True, max_length=200, null=True)),
                ('cannon5', models.CharField(blank=True, max_length=200, null=True)),
                ('political_perspective_of_judge', models.CharField(blank=True, max_length=200, null=True)),
                ('family_connections_in_legal_community', models.CharField(blank=True, max_length=200, null=True)),
                ('tag1', models.CharField(blank=True, max_length=50, null=True)),
                ('tag2', models.CharField(blank=True, max_length=50, null=True)),
                ('tag3', models.CharField(blank=True, max_length=50, null=True)),
                ('total_likes', models.FloatField(default=0.0)),
                ('total_dislikes', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.categories')),
                ('dislikeBy', models.ManyToManyField(blank=True, related_name='userWhoDislike', to=settings.AUTH_USER_MODEL)),
                ('likeBy', models.ManyToManyField(blank=True, related_name='userWhoLike', to=settings.AUTH_USER_MODEL)),
                ('ratedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.judge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='tags',
            field=models.ManyToManyField(blank=True, to='judge.judgeTags'),
        ),
        migrations.CreateModel(
            name='bestInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age', models.IntegerField()),
                ('child_physical_condition', models.CharField(max_length=200)),
                ('child_mental_health', models.CharField(max_length=200)),
                ('father_age', models.IntegerField()),
                ('mother_age', models.IntegerField()),
                ('father_physical_condition', models.CharField(max_length=200)),
                ('father_mental_health', models.CharField(max_length=200)),
                ('mother_physical_condition', models.CharField(max_length=200)),
                ('mother_mental_health', models.CharField(max_length=200)),
                ('relation_with_father', models.CharField(max_length=200)),
                ('relation_with_mother', models.CharField(max_length=200)),
                ('involvement_with_father', models.CharField(max_length=200)),
                ('involvement_with_mother', models.CharField(max_length=200)),
                ('child_needs', models.CharField(max_length=200)),
                ('child_relation_with_siblings', models.CharField(max_length=200)),
                ('child_relation_with_other_family', models.CharField(max_length=200)),
                ('father_roll', models.CharField(max_length=200)),
                ('mother_roll', models.CharField(max_length=200)),
                ('father_support', models.CharField(max_length=200)),
                ('mother_support', models.CharField(max_length=200)),
                ('child_preference', models.CharField(max_length=200)),
                ('ratedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.judge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
