# Generated by Django 3.1.7 on 2021-10-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('general_district_court', models.CharField(blank=True, max_length=100, null=True)),
                ('juvenile_domestic_court', models.CharField(blank=True, max_length=100, null=True)),
                ('circuit_court', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
