# Generated by Django 3.1.7 on 2021-10-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='position',
            new_name='position1',
        ),
        migrations.AddField(
            model_name='judge',
            name='position2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='position3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
