# Generated by Django 3.1.7 on 2021-10-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_judgetags_tagto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='tags',
        ),
    ]
