# Generated by Django 3.1.7 on 2021-10-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_judgerateing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgerateing',
            old_name='score',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='cannon1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='cannon2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='cannon3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='cannon4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='cannon5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='description',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='family_connections_in_legal_community',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='political_perspective_of_judge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
