# Generated by Django 3.1.7 on 2021-10-28 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0003_remove_judge_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgetags',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='usersInTag', to=settings.AUTH_USER_MODEL),
        ),
    ]
