# Generated by Django 3.1.7 on 2021-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20211029_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgerateing',
            name='tag1',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='judgerateing',
            name='tag2',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='judgerateing',
            name='tag3',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
