# Generated by Django 3.1.7 on 2021-10-15 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0004_auto_20211015_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age', models.IntegerField()),
                ('child_physical_condition', models.CharField(max_length=200)),
                ('child_mental_health', models.CharField(max_length=200)),
                ('father_age', models.IntegerField()),
                ('mother_age', models.IntegerField()),
                ('father_physical_condition', models.CharField(max_length=200)),
                ('father_mental_health', models.CharField(max_length=200)),
                ('mother_physical_condition', models.CharField(max_length=200)),
                ('mother_mental_health', models.CharField(max_length=200)),
                ('relation_with_father', models.CharField(max_length=200)),
                ('relation_with_mother', models.CharField(max_length=200)),
                ('involvement_with_father', models.CharField(max_length=200)),
                ('involvement_with_mother', models.CharField(max_length=200)),
                ('child_needs', models.CharField(max_length=200)),
                ('child_relation_with_siblings', models.CharField(max_length=200)),
                ('child_relation_with_other_family', models.CharField(max_length=200)),
                ('father_roll', models.CharField(max_length=200)),
                ('mother_roll', models.CharField(max_length=200)),
                ('father_support', models.CharField(max_length=200)),
                ('mother_support', models.CharField(max_length=200)),
                ('child_preference', models.CharField(max_length=200)),
                ('ratedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.judge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
