# Generated by Django 3.1.7 on 2021-10-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_bestinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='circuit_court',
            new_name='coat_name',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='general_district_court',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='juvenile_domestic_court',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='position1',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='position2',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='position3',
        ),
    ]
