# Generated by Django 3.1.7 on 2021-10-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20211029_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgerateing',
            name='tag1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='judgerateing',
            name='tag2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='judgerateing',
            name='tag3',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
