# Generated by Django 3.1.7 on 2021-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_auto_20211018_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='numberOfRatings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='judge',
            name='obtainScore',
            field=models.IntegerField(default=0),
        ),
    ]
