# Generated by Django 3.1.7 on 2021-10-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20211029_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='state',
            field=models.CharField(default='Virginia', max_length=100),
        ),
    ]
