# Generated by Django 3.1.7 on 2021-10-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20211022_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='totalRating',
            field=models.IntegerField(default=0),
        ),
    ]
