# Generated by Django 3.1.7 on 2021-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_judge_totalrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='obtainScore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='judge',
            name='totalRating',
            field=models.FloatField(default=0),
        ),
    ]
