# Generated by Django 3.1.7 on 2021-10-25 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0009_auto_20211025_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgerateing',
            name='dislikeBy',
            field=models.ManyToManyField(related_name='userWhoDislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='likeBy',
            field=models.ManyToManyField(related_name='userWhoLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='total_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
