# Generated by Django 3.1.7 on 2021-10-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_auto_20211025_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgerateing',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='judgerateing',
            name='total_dislikes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='judgerateing',
            name='total_likes',
            field=models.FloatField(default=0.0),
        ),
    ]
