# Generated by Django 3.1.7 on 2021-10-25 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0011_auto_20211025_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgerateing',
            name='dislikeBy',
            field=models.ManyToManyField(null=True, related_name='userWhoDislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='judgerateing',
            name='likeBy',
            field=models.ManyToManyField(null=True, related_name='userWhoLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
