# Generated by Django 3.1.7 on 2021-10-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0014_auto_20211026_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgerateing',
            name='category',
        ),
        migrations.AddField(
            model_name='judgerateing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.categories'),
        ),
    ]
