# Generated by Django 3.1.7 on 2021-10-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_auto_20211026_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='tags',
            field=models.ManyToManyField(blank=True, to='judge.tags'),
        ),
    ]
