# Generated by Django 3.1.7 on 2021-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0016_judge_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
