# Generated by Django 3.1.7 on 2021-10-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture_id',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user_image/'),
        ),
    ]
